name: Build Flutter App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # این بخش به‌روزرسانی شد
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # <--- تغییر از v3 به v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk